# Generated by Django 4.0.4 on 2022-07-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regi',
            name='materia',
            field=models.CharField(choices=[('mat', 'matematica'), ('fis', 'fisica'), ('bio', 'biologia'), ('qui', 'quimica')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
