# Generated by Django 4.0.4 on 2022-07-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_regi_materia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regi',
            old_name='conter',
            new_name='conteudo',
        ),
        migrations.AddField(
            model_name='regi',
            name='link_video',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
